#set page(width: 210mm, height: 297mm, margin: 20mm)
#set text(font: ("Libertinus Serif",), size: 12pt)
#show raw: set text(font: ("DejaVu Sans Mono",), size: 11.04pt)
#show link: set text(fill: blue)
= Markdown to PDF - Comprehensive Example <markdown-to-pdf-comprehensive-example>

Welcome to the md-to-pdf converter! This document demonstrates all currently supported features.

== Text Formatting <text-formatting>

This converter supports #strong[bold text], #emph[italic text], and #emph[#strong[bold and italic]] text.

You can also use #strike[strikethrough] text.

== Lists <lists>

=== Unordered Lists <unordered-lists>

- First item
- Second item

  - Nested item A
  - Nested item B
- Third item

=== Ordered Lists <ordered-lists>

+ First step
+ Second step
+ Third step

=== Task Lists <task-lists>

- ☐  Task to do
- ☑  Completed task
- ☐  Another task

== Blockquotes <blockquotes>

#block(inset: (left: 12pt), stroke: (left: 1pt + luma(180)))[
This is a blockquote. It can span multiple lines.

You can have multiple paragraphs.
]

== Code <code>

=== Inline Code <inline-code>

Here’s some `inline code` in the middle of a sentence.

=== Code Blocks <code-blocks>

#block(fill: rgb("#f6f8fa"), inset: (x: 10pt, y: 8pt), radius: 4pt, width: 100%, clip: true)[#set text(font: ("DejaVu Sans Mono",), size: 9pt)
#text(fill: rgb("#a71d5d"), weight: "bold")[fn]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#795da3"), weight: "bold")[main]#text(fill: rgb("#323232"))[(]#text(fill: rgb("#323232"))[)]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#323232"))[{]\
#text(fill: rgb("#323232"))[    ]#text(fill: rgb("#323232"))[println!]#text(fill: rgb("#323232"))[(]#text(fill: rgb("#183691"))["]#text(fill: rgb("#183691"))[Hello, world!]#text(fill: rgb("#183691"))["]#text(fill: rgb("#323232"))[)]#text(fill: rgb("#323232"))[;]\
#text(fill: rgb("#323232"))[}]]

#block(fill: rgb("#f6f8fa"), inset: (x: 10pt, y: 8pt), radius: 4pt, width: 100%, clip: true)[#set text(font: ("DejaVu Sans Mono",), size: 9pt)
#text(fill: rgb("#a71d5d"), weight: "bold")[def]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#323232"), weight: "bold")[greet]#text(fill: rgb("#323232"))[(]#text(fill: rgb("#323232"))[name]#text(fill: rgb("#323232"))[)]#text(fill: rgb("#323232"))[:]\
#text(fill: rgb("#323232"))[    ]#text(fill: rgb("#a71d5d"), weight: "bold")[return]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#a71d5d"), weight: "bold")[f]#text(fill: rgb("#183691"))["]#text(fill: rgb("#183691"))[Hello, ]#text(fill: rgb("#323232"))[{]#text(fill: rgb("#323232"))[name]#text(fill: rgb("#323232"))[}]#text(fill: rgb("#183691"))[!]#text(fill: rgb("#183691"))["]\
#h(0pt)\
#text(fill: rgb("#62a35c"))[print]#text(fill: rgb("#323232"))[(]#text(fill: rgb("#323232"))[greet]#text(fill: rgb("#323232"))[(]#text(fill: rgb("#183691"))["]#text(fill: rgb("#183691"))[World]#text(fill: rgb("#183691"))["]#text(fill: rgb("#323232"))[)]#text(fill: rgb("#323232"))[)]]

#block(fill: rgb("#f6f8fa"), inset: (x: 10pt, y: 8pt), radius: 4pt, width: 100%, clip: true)[#set text(font: ("DejaVu Sans Mono",), size: 9pt)
#text(fill: rgb("#a71d5d"), weight: "bold")[function]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#795da3"), weight: "bold")[greet]#text(fill: rgb("#323232"))[(]#text(fill: rgb("#323232"))[name]#text(fill: rgb("#323232"))[)]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#323232"))[{]\
#text(fill: rgb("#323232"))[    ]#text(fill: rgb("#a71d5d"), weight: "bold")[return]#text(fill: rgb("#323232"))[ ]#text(fill: rgb("#183691"))[`]#text(fill: rgb("#183691"))[Hello, ]#text(fill: rgb("#323232"))[\${]#text(fill: rgb("#323232"))[name]#text(fill: rgb("#323232"))[}]#text(fill: rgb("#183691"))[!]#text(fill: rgb("#183691"))[`]#text(fill: rgb("#323232"))[;]\
#text(fill: rgb("#323232"))[}]]

== Links <links>

Visit #link("https://github.com", [GitHub]) or check the #link("https://doc.rust-lang.org/", [Rust documentation]).

== Tables <tables>

#table(
  columns: (1fr, 1fr, 1fr),
  stroke: luma(200),
  inset: 6pt,
  fill: (col, row) => if row == 0 { luma(230) } else { white },
  table.cell(align: left)[#strong[Name]],
  table.cell(align: left)[#strong[Language]],
  table.cell(align: left)[#strong[Stars]],
  table.cell(align: left)[Rust],
  table.cell(align: left)[Systems],
  table.cell(align: left)[80k+],
  table.cell(align: left)[Python],
  table.cell(align: left)[General],
  table.cell(align: left)[50k+],
  table.cell(align: left)[Go],
  table.cell(align: left)[Systems],
  table.cell(align: left)[110k+]
)

== Horizontal Rule <horizontal-rule>

#line(length: 100%)

== Headings <headings>

= Heading 1 (H1) <heading-1-h1>

== Heading 2 (H2) <heading-2-h2>

=== Heading 3 (H3) <heading-3-h3>

==== Heading 4 (H4) <heading-4-h4>

===== Heading 5 (H5) <heading-5-h5>

====== Heading 6 (H6) <heading-6-h6>

== Conclusion <conclusion>

This markdown converter is being actively developed. Stay tuned for more features!

#line(length: 100%)

#emph[Generated by md-to-pdf]


