#set page(width: 210mm, height: 297mm, margin: 20mm)
#set text(font: ("Libertinus Serif",), size: 12pt)
#show raw: set text(font: ("DejaVu Sans Mono",), size: 11.04pt)
#show link: set text(fill: blue)
#pagebreak()
= Table of Contents
- Markdown to PDF - Comprehensive Example
  - Text Formatting
  - Lists
    - Unordered Lists
    - Ordered Lists
    - Task Lists
  - Blockquotes
  - Code
    - Inline Code
    - Code Blocks
  - Links
  - Tables
  - Horizontal Rule
  - Headings
- Heading 1 (H1)
  - Heading 2 (H2)
    - Heading 3 (H3)
      - Heading 4 (H4)
        - Heading 5 (H5)
          - Heading 6 (H6)
  - Conclusion
#pagebreak()

= Markdown to PDF - Comprehensive Example

Welcome to the md-to-pdf converter! This document demonstrates all currently supported features.

== Text Formatting

This converter supports #strong[bold text], #emph[italic text], and #emph[#strong[bold and italic]] text.

You can also use #strike[strikethrough] text.

== Lists

=== Unordered Lists

- First item
- Second item

- Nested item A
- Nested item B
- Third item

=== Ordered Lists

+ First step
+ Second step
+ Third step

=== Task Lists


== Blockquotes

#block(inset: (left: 12pt), stroke: (left: 1pt + luma(180)))[
This is a blockquote. It can span multiple lines.

You can have multiple paragraphs.
]

== Code

=== Inline Code

Here’s some `inline code` in the middle of a sentence.

=== Code Blocks

#block(fill: luma(245), inset: 10pt, radius: 4pt)[
#text(fill: luma(90), size: 10pt)[rust]
#text(font: ("DejaVu Sans Mono",), [fn main() \{     println!(\"Hello, world!\"); \} ])
]

#block(fill: luma(245), inset: 10pt, radius: 4pt)[
#text(fill: luma(90), size: 10pt)[python]
#text(font: ("DejaVu Sans Mono",), [def greet(name):     return f\"Hello, \{name\}!\"  print(greet(\"World\")) ])
]

#block(fill: luma(245), inset: 10pt, radius: 4pt)[
#text(fill: luma(90), size: 10pt)[javascript]
#text(font: ("DejaVu Sans Mono",), [function greet(name) \{     return `Hello, $\{name\}!`; \} ])
]

== Links

Visit #link("https://github.com", [GitHub]) or check the #link("https://doc.rust-lang.org/", [Rust documentation]).

== Tables

#table(
  columns: 3,
  stroke: luma(180),
  inset: 6pt,
  align: left,
  [Name],
  [Language],
  [Stars],
  [Rust],
  [Systems],
  [80k+],
  [Python],
  [General],
  [50k+],
  [Go],
  [Systems],
  [110k+]
)

== Horizontal Rule

#line(length: 100%)

== Headings

= Heading 1 (H1)

== Heading 2 (H2)

=== Heading 3 (H3)

==== Heading 4 (H4)

===== Heading 5 (H5)

====== Heading 6 (H6)

== Conclusion

This markdown converter is being actively developed. Stay tuned for more features!

#line(length: 100%)

#emph[Generated by md-to-pdf]


